project:
  type: website
  output-dir: docs

website:
  title: "Julia Aceron Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Data Viz.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

  
# ~ additional metadata excluded for brevity ~
editor: visual

