project:
  type: website
  output-dir: docs

website:
  title: "Julia Aceron Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right: 
      - text: Data Viz 
      - menu: 
        - text: Summer Movies Analysis
        - SummerMovies.qmd
        - text: Valentines Day Consumerism
        - ValentinesDay.qmd
        - text: Show Synopses and their Weekly Grosses 
        - MusicalSynopses.qmd
        - text: Legalization of Marijuana Simulation 
        - MarijuanaSimulation.qmd
        - text: Mean Absorbance and Frequency from WAI Database 
        - WAIDatasetSQL.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

  
# ~ additional metadata excluded for brevity ~
editor: visual

