---
title: "Data Viz" 
description: |
  Analysis of Summer Movies data from TidyTuesday
author: Julia Aceron
date: September 18, 2024
format: html
execute:
  warning: false
  message: false
---

```{r echo = FALSE, include= FALSE}
# Option 2: Read directly from GitHub

summer_movie_genres <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-07-30/summer_movie_genres.csv')
summer_movies <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-07-30/summer_movies.csv')
```

```{r}
library(tidyverse)
ggplot(data = summer_movies) +
  geom_point(aes(x = year, y = average_rating, color = year)) +
  labs (
    x = "Years of Release",
    y = "Average Rating of Movies"
  )
  ggtitle("Years of Movies and their Average Rating")

```

```{r echo = FALSE, include= FALSE}
historical_spending <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-02-13/historical_spending.csv')
gifts_age <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-02-13/gifts_age.csv')
gifts_gender <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-02-13/gifts_gender.csv')

```

```{r}
library(tidyverse)
ggplot(data = historical_spending) +
  geom_line(aes(x = Year, y = PercentCelebrating, color = Year)) +
  labs (
    x = "Year",
    y = "Percent of People Celebrating"
  )
  ggtitle("Trend of People who Celebrate Valentine's Day") 
```

Tidy Tuesday Dataset Sources

[Summer Movies](https://developer.imdb.com/non-commercial-datasets/)

[Valentine's Day Consumer Data](https://nrf.com/research-insights/holiday-data-and-trends/valentines-day/valentines-day-data-centerhttps://nrf.com/research-insights/holiday-data-and-trends/valentines-day/valentines-day-data-center)
